openapi: 3.0.3
info:
  title: Видеохостинг API
  description: API для управления каналами и пользователями видеохостинга
  version: 0.0.1
servers:
  - url: http://localhost:8080/api/v0.0.1

tags:
  - name: Channels
    description: Операции, связанные с каналами
  - name: Users
    description: Операции, связанные с пользователями

paths:
  /users:
    get:
      tags:
        - Users
      summary: Получить список всех пользователей
      description: Возвращает список всех зарегистрированных пользователей
      responses:
        '200':
          description: Список пользователей
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'

    post:
      tags:
        - Users
      summary: Создать нового пользователя
      description: Создает нового пользователя с никнеймом, именем и почтой
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '201':
          description: Пользователь успешно создан
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Неверный запрос

  /users/{nickname}:
    get:
      tags:
        - Users
      summary: Получить информацию о пользователе
      description: Возвращает информацию о пользователе по указанному никнейму
      parameters:
        - in: path
          name: nickname
          required: true
          schema:
            type: string
            example: "petya1234"
          description: Никнейм пользователя
      responses:
        '200':
          description: Информация о пользователе
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: Пользователь не найден

    put:
      tags:
        - Users
      summary: Обновить информацию о пользователе
      description: Обновляет информацию пользователя по указанному никнейму
      parameters:
        - in: path
          name: nickname
          required: true
          schema:
            type: string
            example: "petya1234"
          description: Никнейм пользователя
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: Информация о пользователе успешно обновлена
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: Пользователь не найден

  /channels:
    post:
      tags:
        - Channels
      summary: Создать новый канал
      description: Создает новый канал с указанными данными
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Channel'
      responses:
        '201':
          description: Канал успешно создан
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Channel'
        '400':
          description: Неверный запрос

    get:
      tags:
        - Channels
      summary: Получить список всех каналов
      description: Возвращает список всех каналов с поддержкой пагинации и фильтрации по названию, языку, категории
      parameters:
        - in: query
          name: name
          schema:
            type: string
            example: "Tech Insights"
          description: Фильтр по названию канала
        - in: query
          name: language
          schema:
            type: string
            example: "RU"
          description: Фильтр по языку канала
        - in: query
          name: category
          schema:
            type: string
            example: "Технологии"
          description: Фильтр по категории канала
        - in: query
          name: page
          schema:
            type: integer
            example: 1
          description: Номер страницы
        - in: query
          name: size
          schema:
            type: integer
            example: 10
          description: Количество элементов на странице
      responses:
        '200':
          description: Список каналов
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                      description: Название канала
                      example: "Tech Insights"
                    subscriberCount:
                      type: integer
                      description: Количество подписчиков
                      example: 150
                    language:
                      type: string
                      description: Основной язык канала
                      example: "RU"
                    avatarUrl:
                      type: string
                      description: Ссылка на аватарку канала
                      example: "http://example.com/avatar.jpg"
                    category:
                      type: string
                      description: Категория канала
                      example: "Технологии"

  /channels/{channelName}:
    get:
      tags:
        - Channels
      summary: Получить информацию о канале
      description: Возвращает подробную информацию о канале
      parameters:
        - in: path
          name: channelName
          required: true
          schema:
            type: string
            example: "Tech Insights"
          description: Название канала
      responses:
        '200':
          description: Подробная информация о канале
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Channel'

    put:
      tags:
        - Channels
      summary: Обновить информацию о канале
      description: Обновляет информацию о канале по указанному названию
      parameters:
        - in: path
          name: channelName
          required: true
          schema:
            type: string
            example: "Tech Insights"
          description: Название канала
            type
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Channel'
      responses:
        '200':
          description: Информация о канале успешно обновлена
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Channel'
        '404':
          description: Канал не найден

  /channels/{channelName}/subscribe:
    post:
      tags:
        - Channels
      summary: Подписать пользователя на канал
      description: Подписывает пользователя на канал
      parameters:
        - in: path
          name: channelName
          required: true
          schema:
            type: string
            example: "Tech Insights"
          description: Название канала
        - in: query
          name: nickname
          required: true
          schema:
            type: string
            example: "petya1234"
          description: Никнейм пользователя
      responses:
        '200':
          description: Пользователь успешно подписан на канал
        '404':
          description: Канал или пользователь не найдены

  /channels/{channelName}/unsubscribe:
    post:
      tags:
        - Channels
      summary: Отписать пользователя от канала
      description: Отписывает пользователя от канала
      parameters:
        - in: path
          name: channelName
          required: true
          schema:
            type: string
            example: "Tech Insights"
          description: Название канала
        - in: query
          name: nickname
          required: true
          schema:
            type: string
            example: "petya1234"
          description: Никнейм пользователя
      responses:
        '200':
          description: Пользователь успешно отписан от канала
        '404':
          description: Канал или пользователь не найдены

  /users/{nickname}/subscriptions:
    get:
      tags:
        - Users
      summary: Получить подписки пользователя
      description: Возвращает список всех каналов, на которые подписан пользователь
      parameters:
        - in: path
          name: nickname
          required: true
          schema:
            type: string
            example: "petya1234"
          description: Никнейм пользователя
      responses:
        '200':
          description: Список подписок пользователя
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                example: ["Tech Insights"]

components:
  schemas:
    User:
      type: object
      properties:
        nickname:
          type: string
          description: Никнейм пользователя
          example: "petya1234"
        name:
          type: string
          description: Имя пользователя
          example: "Petya Petrov"
        email:
          type: string
          description: Электронная почта пользователя
          example: "petya@gmail.com"


    Channel:
      type: object
      properties:
        name:
          type: string
          description: Название канала
          example: "Tech Insights"
        description:
          type: string
          description: Краткое описание канала
          example: "Канал о новинках технологий"
        author:
          $ref: '#/components/schemas/User'
        subscriberCount:
          type: integer
          description: Количество подписчиков
          example: 150
        language:
          type: string
          description: Основной язык канала
          example: "RU"
        avatarUrl:
          type: string
          description: Ссылка на аватарку канала
          example: "http://example.com/avatar.jpg"
        category:
          type: string
          description: Категория канала
          example: "Технологии"
        createdDate:
          type: string
          format: date-time
          description: Дата создания канала

