openapi: 3.0.3
info:
  title: Видеохостинг API
  description: API для управления каналами и пользователями видеохостинга
  version: 0.0.1
servers:
  - url: http://localhost:8080/api/v0.0.1

tags:
  - name: Channels
    description: Операции, связанные с каналами
  - name: Users
    description: Операции, связанные с пользователями

paths:
  /users:
    get:
      tags:
        - Users
      summary: Получить список всех пользователей
      description: Возвращает список всех зарегистрированных пользователей
      responses:
        '200':
          description: Список пользователей
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'

    post:
      tags:
        - Users
      summary: Создать нового пользователя
      description: Создает нового пользователя с никнеймом, именем и почтой
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '201':
          description: Пользователь успешно создан
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Неверный запрос

  /users/{id}:
    get:
      tags:
        - Users
      summary: Получить информацию о пользователе
      description: Возвращает информацию о пользователе по указанному никнейму
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            example: 1
          description: Id пользователя
      responses:
        '200':
          description: Информация о пользователе
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: Пользователь не найден

    put:
      tags:
        - Users
      summary: Обновить информацию о пользователе
      description: Обновляет информацию пользователя по указанному никнейму
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            example: 1
          description: Никнейм пользователя
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserDto'
      responses:
        '200':
          description: Информация о пользователе успешно обновлена
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: Пользователь не найден

    patch:
      tags:
        - Users
      summary: Частичное обновление информации о пользователе
      description: Обновляет только те поля пользователя, которые указаны в запросе
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            example: 1
          description: Id пользователя
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserDto'
      responses:
        '200':
          description: Информация о пользователе успешно обновлена
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: Пользователь не найден

  /channels:
    post:
      tags:
        - Channels
      summary: Создать новый канал
      description: Создает новый канал с указанными данными.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChannelCreate'
      responses:
        '201':
          description: Канал успешно создан
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Channel'
        '404':
          description: Пользователь или категория не найдены
        '400':
          description: Неверный запрос

    get:
      tags:
        - Channels
      summary: Получить список всех каналов
      description: Возвращает список всех каналов с поддержкой пагинации и фильтрации по названию, языку, категории, а также информацию о количестве страниц и записей
      parameters:
        - in: query
          name: name
          schema:
            type: string
            example: "Tech Insights"
          description: Фильтр по названию канала
        - in: query
          name: language
          schema:
            type: string
            example: "RU"
          description: Фильтр по языку канала
        - in: query
          name: categoryId
          schema:
            type: integer
            example: 1
          description: Фильтр по id категории канала
        - in: query
          name: page
          schema:
            type: integer
            example: 1
          description: Номер страницы
        - in: query
          name: size
          schema:
            type: integer
            example: 10
          description: Количество элементов на странице
      responses:
        '200':
          description: Список каналов с информацией о пагинации
          content:
            application/json:
              schema:
                type: object
                properties:
                  totalRecords:
                    type: integer
                    description: Общее количество записей
                    example: 100
                  totalPages:
                    type: integer
                    description: Общее количество страниц
                    example: 10
                  channels:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                          description: Название канала
                          example: "Tech Insights"
                        subscriberCount:
                          type: integer
                          description: Количество подписчиков
                          example: 150
                        language:
                          type: string
                          description: Основной язык канала
                          example: "RU"
                        categoryId:
                          type: integer
                          description: ID категории канала
                          example: 1
                        avatar:
                          type: string
                          description: Аватар в формате base64
                          example: "data:image/png;base64,iVBORw0K..."

  /channels/{id}:
    get:
      tags:
        - Channels
      summary: Получить информацию о канале
      description: Возвращает подробную информацию о канале по ID, включая количество подписчиков
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            example: 1
          description: ID канала
      responses:
        '200':
          description: Подробная информация о канале
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Channel'
        '404':
          description: Канал не найден

    put:
      tags:
        - Channels
      summary: Обновить информацию о канале
      description: Обновляет информацию о канале по ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            example: 1
          description: ID канала
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChannelUpdate'
      responses:
        '200':
          description: Информация о канале успешно обновлена
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Channel'
        '404':
          description: Канал не найден

    patch:
      tags:
        - Channels
      summary: Частичное обновление информации о канале
      description: Обновляет только те поля канала, которые указаны в запросе
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            example: 1
          description: ID канала
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChannelUpdate'
      responses:
        '200':
          description: Информация о канале успешно частично обновлена
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Channel'
        '404':
          description: Канал не найден

  /channels/{id}/subscriptions:
    post:
      tags:
        - Channels
      summary: Подписать пользователя на канал
      description: Подписывает пользователя на канал по ID канала и ID пользователя
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            example: 1
          description: ID канала
        - in: query
          name: userId
          required: true
          schema:
            type: integer
            example: 1
          description: ID пользователя
      responses:
        '200':
          description: Пользователь успешно подписан на канал
        '404':
          description: Канал или пользователь не найден

    delete:
      tags:
        - Channels
      summary: Отписать пользователя от канала
      description: Отписывает пользователя от канала по ID канала и ID пользователя
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            example: 1
          description: ID канала
        - in: query
          name: userId
          required: true
          schema:
            type: integer
            example: 1
          description: ID пользователя
      responses:
        '200':
          description: Пользователь успешно отписан от канала
        '404':
          description: Канал или пользователь не найден

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          description: ID пользователя
        nickname:
          type: string
          description: Никнейм пользователя
        name:
          type: string
          description: Имя пользователя
        email:
          type: string
          format: email
          description: Email пользователя

    UserDto:
      type: object
      properties:
        nickname:
          type: string
          description: Никнейм пользователя
        name:
          type: string
          description: Имя пользователя
        email:
          type: string
          format: email
          description: Email пользователя

    ChannelCreate:
      type: object
      properties:
        name:
          type: string
          description: Название канала
        description:
          type: string
          description: Описание канала
        authorId:
          type: integer
          description: ID автора канала
        language:
          type: string
          description: Язык канала
        categoryId:
          type: integer
          description: ID категории канала
        avatar:
          type: string
          description: Аватар в формате base64

    ChannelUpdate:
      type: object
      properties:
        name:
          type: string
          description: Название канала
        description:
          type: string
          description: Описание канала
        language:
          type: string
          description: Язык канала
        categoryId:
          type: integer
          description: ID категории канала
        avatar:
          type: string
          description: Аватар в формате base64

    Channel:
      type: object
      properties:
        id:
          type: integer
          description: ID канала
          example: 1
        authorId:
          type: integer
          description: ID автора канала
          example: 1
        name:
          type: string
          description: Название канала
          example: "Tech Insights"
        description:
          type: string
          description: Описание канала
          example: "Канал о технике"
        language:
          type: string
          description: Язык канала
          example: "RU"
        categoryId:
          type: integer
          description: ID категории, к которой относится канал
          example: 2
        avatar:
          type: string
          description: Аватар канала в формате base64
          example: "data:image/png;base64,iVBORw0K..."
        createdAt:
          type: string
          format: date-time
          description: Дата и время создания канала
          example: "2024-10-12T08:30:00Z"
